/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateAdvertiseArgs } from "./CreateAdvertiseArgs";
import { UpdateAdvertiseArgs } from "./UpdateAdvertiseArgs";
import { DeleteAdvertiseArgs } from "./DeleteAdvertiseArgs";
import { AdvertiseFindManyArgs } from "./AdvertiseFindManyArgs";
import { AdvertiseFindUniqueArgs } from "./AdvertiseFindUniqueArgs";
import { Advertise } from "./Advertise";
import { AdvertiseService } from "../advertise.service";

@graphql.Resolver(() => Advertise)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class AdvertiseResolverBase {
  constructor(
    protected readonly service: AdvertiseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Advertise",
    action: "read",
    possession: "any",
  })
  async _advertisesMeta(
    @graphql.Args() args: AdvertiseFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Advertise])
  @nestAccessControl.UseRoles({
    resource: "Advertise",
    action: "read",
    possession: "any",
  })
  async advertises(
    @graphql.Args() args: AdvertiseFindManyArgs
  ): Promise<Advertise[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Advertise, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Advertise",
    action: "read",
    possession: "own",
  })
  async advertise(
    @graphql.Args() args: AdvertiseFindUniqueArgs
  ): Promise<Advertise | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Advertise)
  @nestAccessControl.UseRoles({
    resource: "Advertise",
    action: "create",
    possession: "any",
  })
  async createAdvertise(
    @graphql.Args() args: CreateAdvertiseArgs
  ): Promise<Advertise> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Advertise)
  @nestAccessControl.UseRoles({
    resource: "Advertise",
    action: "update",
    possession: "any",
  })
  async updateAdvertise(
    @graphql.Args() args: UpdateAdvertiseArgs
  ): Promise<Advertise | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Advertise)
  @nestAccessControl.UseRoles({
    resource: "Advertise",
    action: "delete",
    possession: "any",
  })
  async deleteAdvertise(
    @graphql.Args() args: DeleteAdvertiseArgs
  ): Promise<Advertise | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
